import { createClient } from '@supabase/supabase-js';

// For now, using placeholder values
// You'll replace these with real values from supabase.com
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://placeholder.supabase.co';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'placeholder-key';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Database types (will be auto-generated by Supabase CLI later)
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          wallet_address: string;
          username: string | null;
          bio: string | null;
          avatar_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          wallet_address: string;
          username?: string | null;
          bio?: string | null;
          avatar_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          wallet_address?: string;
          username?: string | null;
          bio?: string | null;
          avatar_url?: string | null;
          created_at?: string;
        };
      };
      platforms: {
        Row: {
          id: number;
          name: string;
          chain: string;
          token: string;
          contract_address: string | null;
        };
      };
      user_platform_stats: {
        Row: {
          id: string;
          user_id: string;
          platform_id: number;
          total_bets: number;
          wins: number;
          losses: number;
          win_rate: number;
          volume: string;
          score: number;
          last_updated: string;
        };
      };
      bets: {
        Row: {
          id: string;
          user_id: string;
          platform_id: number;
          market_id: string;
          position: string;
          amount: string;
          claimed_amount: string | null;
          won: boolean | null;
          tx_hash: string | null;
          block_number: number | null;
          timestamp: string | null;
          created_at: string;
        };
      };
      copy_follows: {
        Row: {
          id: string;
          follower_id: string;
          trader_id: string;
          platform_id: number | null;
          allocation_percentage: number;
          max_bet_amount: string;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          follower_id: string;
          trader_id: string;
          platform_id?: number | null;
          allocation_percentage: number;
          max_bet_amount: string;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          follower_id?: string;
          trader_id?: string;
          platform_id?: number | null;
          allocation_percentage?: number;
          max_bet_amount?: string;
          is_active?: boolean;
          created_at?: string;
        };
      };
      copy_trades: {
        Row: {
          id: string;
          copy_follow_id: string;
          original_bet_id: string;
          copied_bet_id: string;
          executed_at: string;
        };
      };
    };
  };
}
